name: Build and Deploy

on:
    push:
        branches: [ "frankenbranch" ]

env:
   # See: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
   IMAGE_NAME: 5etools

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         # See: https://stackoverflow.com/a/58178121
         -  name: Set Env
            run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

         -  name: Archive Release
            run: |
               zip -r 5etools-${{ env.RELEASE_VERSION }}.zip . -x '*.git*' '*node_modules*' '*.github*' '*img*'

         -  name: Set Deployed Flag
            run: |
               bash ./.github/set-deployed-flag.sh ${{ env.RELEASE_VERSION }}

         # Remove entries from the `.gitignore` so the gh-pages action can correctly add+commit them to the pages branch
         -  name: Build Service Worker
            run: |
               node --version
               npm --version
               npm i
               npm run build:sw:prod
               sed -i 's/sw.js//g' .gitignore
               sed -i 's/sw-injector.js//g' .gitignore

         -  name: Build SEO Pages
            env:
               VET_BASE_SITE_URL: https://5etools-mirror-1.github.io/
               VET_SEO_IS_SKIP_UA_ETC: true
            run: |
               npm run build:seo -- ${{ env.RELEASE_VERSION }}

         # See: https://github.com/JamesIves/github-pages-deploy-action
         -  name: Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v4
            with:
               branch: frankenbranch
               folder: .

     
